# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKUSER }}
        password: ${{ secrets.DOCKPASS }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: jwiercinski/goazure:latest

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jwgoserver'
        slot-name: 'production'
        publish-profile: ${{ secrets.PUBLISHPROFILE }}
        images: 'index.docker.io/jwiercinski/goazure:${{ github.sha }}'

    - name: Send mail
      if: ${{ success() }}
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Status budowy aplikacji Go
        to: ${{ secrets.MAIL_USERNAME }}
        from: ${{ secrets.MAIL_USERNAME }}
        body: Build i deployment zakończony powodzeniem!


