# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jwgoserver

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  simplebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...
      
    - name: Send mail
      if: ${{ success() }}
      uses: dawidd6/action-send-mail@v2
      with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Status budowy aplikacji Go
          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}
          body: Standardowy build zakończony powodzeniem!

  build:
    runs-on: 'ubuntu-latest'
    needs: simplebuild

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca965c2835d844f7a065f54869c9c3db }}
        password: ${{ secrets.AzureAppService_ContainerPassword_829533990ecb4fc59c800ab441741faf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca965c2835d844f7a065f54869c9c3db }}/goazure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jwgoserver'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cc69580249774c04a25c37acbe59ff81 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca965c2835d844f7a065f54869c9c3db }}/goazure:${{ github.sha }}'
