# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  simplebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...
      
    - name: Send mail
      if: ${{ success() }}
      uses: dawidd6/action-send-mail@v2
      with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Status budowy aplikacji Go
          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}
          body: Standardowy build zakończony powodzeniem!

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_32abc864fb3c4137bcc0a9162bf35d5b }}
          password: ${{ secrets.AzureAppService_ContainerPassword_bbdeb53f427f4db98615a5cb9729a90b }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_32abc864fb3c4137bcc0a9162bf35d5b }}/goazure:${{ github.sha }}
          file: ./Dockerfile

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'jwgoserver'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_ef7c2b877d9049ff84b15139851f7b2a }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_32abc864fb3c4137bcc0a9162bf35d5b }}/goazure:${{ github.sha }}'
